INSERT INTO public.users(
	name, id_type_user)
	VALUES	
			 ('AGEN, S. A.',1),
			 ('AGRICOLA LA ENTRADA, S. A.',1),
			 ('AGRO COMERCIALIZADORA DEL POLOCHIC, S. A.',1),
			 ('AGROFORESTAL EL CEDRO, S. A.',1),
			 ('AGROGENERADORA, S. A.',1),
			 ('AGROINDUSTRIAL PIEDRA NEGRA, S. A.',1),
			 ('AGROPECUARIA ALTORR, S. A.',1),
			 ('AGROPROP, S. A.',1),
			 ('AGUILAR, ARIMANY, ASOCIADOS CONSULTORES, S. A.',1),
			 ('ALTERNATIVA DE ENERGIA RENOVABLE, S. A.',1),
			 ('ANACAPRI, S. A.',1),
			 ('BIOMASS ENERGY, S. A.',1),
			 ('CAUDALES RENOVABLES S. A.',1),
			 ('CENTRAL AGRO INDUSTRIAL GUATEMALTECA, S. A.',1),
			 ('CINCO M, S. A.',1),
			 ('COMERCIALIZADORA COMERTITLAN, S. A.',1),
			 ('COMERCIALIZADORA DE ENERGIA PARA EL DESARROLLO, S. A.',1),
			 ('COMERCIALIZADORA ELECTRICA DE GUATEMALA, S.A.',1),
			 ('COMERCIALIZADORA ELECTRICA DEL PACIFICO, S. A.',1),
			 ('COMERCIALIZADORA ELECTRONOVA, S. A.',1),
			 ('COMERCIALIZADORA ORAZUL ENERGY DE CENTRO AMERICA, LTDA.',1),
			 ('COMPANIA AGRICOLA INDUSTRIAL SANTA ANA, S. A.',1),
			 ('COMPAÑIA ELECTRICA LA LIBERTAD, S. A.',1),
			 ('COMPAÑÍA AGRÍCOLA, O.V., S. A.',1),
			 ('COMPAÑÍA DE MONTAJES ELECTROMECANICOS, S. A.',1),
			 ('COMPRA DE MATERIAS PRIMAS, S. A.',1),
			 ('CORALITO, S. A.',1),
			 ('CUESTAMORAS COMERCIALIZADORA ELÉCTRICA, S.A.',1),
			 ('DESARROLLOS LAS UVITAS, S. A.',1),
			 ('EL PILAR, S. A.',1),
			 ('ELECTRO GENERACION, S. A.',1),
			 ('EMPRESA DE COMERCIALIZACION DE ENERGIA ELECTRICA DEL INDE',1),
			 ('EMPRESA DE GENERACION DE ENERGIA ELECTRICA DEL INDE',1),
			 ('ENEL GREEN POWER GUATEMALA, S. A.',1),
			 ('ENERGIA DEL CARIBE, S. A.',1),
			 ('ENERGIA LIMPIA DE GUATEMALA, S. A.',1),
			 ('ENERGIAS DEL OCOSITO, S. A.',1),
			 ('ENERGIAS RENOVABLES AMLO, S. A.',1),
			 ('ENERGIAS SAN JOSE, S. A.',1),
			 ('ENERGÍA DE LA TIERRA, S. A.',1),
			 ('EOLICO SAN ANTONIO EL SITIO, S.A.',1),
			 ('ESI, S. A.',1),
			 ('GENEPAL, S. A.',1),
			 ('GENERADORA  DEL ATLANTICO, S. A.',1),
			 ('GENERADORA DE ENERGIA EL PRADO, S. A.',1),
			 ('GENERADORA DE OCCIDENTE, LTDA.',1),
			 ('GENERADORA DEL ESTE, S. A.',1),
			 ('GENERADORA ELECTRICA DEL NORTE LTDA.',1),
			 ('GENERADORA ELECTRICA LA PAZ, S. A.',1),
			 ('GENERADORA ELECTRICA LAS VICTORIAS, S. A.',1),
			 ('GRUPO CUTZÁN, S. A.',1),
			 ('GRUPO GENERADOR DE ORIENTE, S. A.',1),
			 ('HIDRO JUMINA, S. A.',1),
			 ('HIDRO VICTORIA, S. A.',1),
			 ('HIDRO XACBAL',1),
			 ('HIDROELECTRICA CANDELARIA, S. A.',1),
			 ('HIDROELECTRICA EL BROTE, S. A.',1),
			 ('HIDROELECTRICA EL COBANO, S. A.',1),
			 ('HIDROELECTRICA EL COROZO',1),
			 ('HIDROELECTRICA MAXANAL, S.A.',1),
			 ('HIDROELECTRICA RAAXHA, S. A.',1),
			 ('HIDROELECTRICA SAC-JA, S. A.',1),
			 ('HIDROELECTRICA SAMUC, S. A.',1),
			 ('HIDROELECTRICA SANTA ANITA, S.A.',1),
			 ('HIDROELÉCTRICA CARMEN AMALIA, S. A.',1),
			 ('HIDROELÉCTRICA CHOLIVÁ, S. A.',1),
			 ('HIDROLECT, S. A.',1),
			 ('HIDROPOWER SDMM, S. A.',1),
			 ('HIDROSACPUR, S. A.',1),
			 ('HIDROXOCOBIL, S. A.',1),
			 ('INDUSTRIAS DE BIOGAS, S. A.',1),
			 ('INGENIO LA UNION, S.A.',1),
			 ('INGENIO MAGDALENA, S.A.',1),
			 ('INGENIO PALO GORDO, S. A.',1),
			 ('INGENIO TULULA, S. A.',1),
			 ('INVERSIONES ATENAS, S. A.',1),
			 ('INVERSIONES NACIMIENTO, S. A.',1),
			 ('INVERSIONES PASABIEN, S. A.',1),
			 ('ION ENERGY, S. A.',1),
			 ('JAGUAR ENERGY GUATEMALA LLC.',1),
			 ('LEEVERG, S. A.',1),
			 ('LUZ Y FUERZA ELECTRICA DE GUATEMALA, LTDA.',1),
			 ('MAYORISTAS DE ELECTRICIDAD, S.A.',1),
			 ('MERELEC GUATEMALA, S. A.',1),
			 ('MONTE MARIA, S. A.',1),
			 ('ORAZUL ENERGY GUATEMALA Y CIA. S. C. A.',1),
			 ('OSCANA, S. A.',1),
			 ('OXEC II, S. A.',1),
			 ('OXEC, S. A.',1),
			 ('PANTALEON, S.A.',1),
			 ('PAPELES ELABORADOS, S. A.',1),
			 ('PROYECTOS SOSTENIBLES DE GUATEMALA, S. A.',1),
			 ('PUERTO QUETZAL POWER LLC',1),
			 ('PUNTA DEL CIELO, S. A.',1),
			 ('REGIONAL ENERGETICA, S. A.',1),
			 ('RENACE, S. A.',1),
			 ('RENOVABLES DE GUATEMALA, S. A.',1),
			 ('SAN DIEGO, S. A.',1),
			 ('SERVICIOS CM, S. A.',1),
			 ('SERVICIOS EN GENERACION, S. A.',1),
			 ('SIBO, S. A.',1),
			 ('SOLARIS GUATEMALA, S. A.',1),
			 ('TECNOGUAT, S. A.',1),
			 ('TERMICA, S. A.',1),
			 ('TRANSMISIÓN DE ELECTRICIDAD, S. A.',1),
			 ('TUNCAJ, S. A.',1),
			 ('VIENTO BLANCO, S. A.',1),
			 ('VISION DE AGUILA, S. A.',1),
			 ('XOLHUITZ PROVIDENCIA, S. A.',1),
			 
			 
			 ('Agencias J. I. Cohen',2),
			 ('Alternativa De Energia Renovable, S. A. (Exportacion La Vega)',2),
			 ('Alternativa De Energia Renovable, S. A. (Exportacion Moyuta)',2),
			 ('Alternativa De Energia Renovable, S. A. (Exportacion México)',2),
			 ('Alternativa De Energia Renovable, S. A. (Exportacion Panaluya)',2),
			 ('Biomass Energy, S. A. (Exportación Panaluya)',2),
			 ('Central Comercializadora De Energia Electrica, S.A.',2),
			 ('Comercializadora Centroamericana De Energia La Ceiba, S. A.',2),
			 ('Comercializadora De Energia Para El Desarrollo, S. A.',2),
			 ('Comercializadora De Energía San Diego, S. A.',2),
			 ('Comercializadora Electrica De Guatemala, S. A. (Exportación Panaluya)',2),
			 ('Comercializadora Electrica De Guatemala, S.A.',2),
			 ('Comercializadora Electrica Del Pacifico, S. A.',2),
			 ('Comercializadora Electrica La Union, S. A.',2),
			 ('Comercializadora Electronova, S. A.',2),
			 ('Comercializadora Guatemalteca Mayorista De Electricidad S.A.',2),
			 ('Compañía Agrícola Industrial Santa Ana, S.A. (Exportación Moyuta)',2),
			 ('Compañía Agrícola Industrial Santa Ana, S.A. (Exportación Panaluya)',2),
			 ('Consorcio Energético MaayatAan, S. A.',2),
			 ('Corporación De Electricidad Centroamericana, S. A.',2),
			 ('Cova Energy, S. A.',2),
			 ('Cuestamoras Comercializadora Eléctrica, S.A.',2),
			 ('Cuestamoras Comercializadora Eléctrica, S.A. (Exportación Moyuta)',2),
			 ('Distribuidora De Electricidad De Occidente, S. A.',2),
			 ('Distribuidora De Electricidad De Oriente, S. A.',2),
			 ('Econoenergía, S. A.',2),
			 ('Empresa de Generación de Energía Eléctrica del Inde (demanda puntos EEMs)',2),
			 ('Empresa De Generación De Energía Eléctrica Del Inde (Exportación Moyuta)',2),
			 ('Empresa De Generación De Energía Eléctrica Del Inde (Exportación Panaluya)',2),
			 ('Empresa De Transporte Y Control De Energia Electrica',2),
			 ('Empresa Electrica De Guatemala, S. A.',2),
			 ('Empresa Municipal Rural De Electricidad De Playa Grande',2),
			 ('Empresa Propietaria De La Red, S. A., Sucursal Guatemala',2),
			 ('Enel Green Power Guatemala, S. A.',2),
			 ('Enel Green Power Guatemala, S. A. (Exportación La Vega)',2),
			 ('Enel Green Power Guatemala, S. A. (Exportación Moyuta)',2),
			 ('Enel Green Power Guatemala, S. A. (Exportación Panaluya)',2),
			 ('Energias San Jose, S. A. (Exportación La Vega)',2),
			 ('Energias San Jose, S. A. (Exportación Moyuta)',2),
			 ('Energias San Jose, S. A. (Exportación Panaluya)',2),
			 ('Entre Rios Sustainable Woods, S. A.',2),
			 ('Entre Rios, S. A.',2),
			 ('Genepal, S. A. (Exportación La Vega)',2),
			 ('Genepal, S. A. (Exportación Panaluya)',2),
			 ('Guatemala De Moldeados, S. A.',2),
			 ('Hidro Xacbal (Exportación Panaluya)',2),
			 ('Ingenio La Union, S. A. (Exportación Panaluya)',2),
			 ('Ingenio Tulula, S. A. (Exportación Panaluya)',2),
			 ('Inmobiliaria La Roca, S. A.',2),
			 ('Instituto De Recreacion De Los Trabajadores (Gusirtne0000001)',2),
			 ('Instituto Nacional De Electrificacion (Edificio Inde)',2),
			 ('Inversiones Nacimiento, S. A.',2),
			 ('Ion Energy, S. A.',2),
			 ('Jaguar Energy Guatemala Llc. (Exportación La Vega)',2),
			 ('Jaguar Energy Guatemala Llc. (Exportación Panaluya)',2),
			 ('Mayoristas De Electricidad, S.A.',2),
			 ('Orazul Energy Guatemala Y Cia. S. C. A.',2),
			 ('Orazul Energy Guatemala Y Cia. S. C. A. (Exportación Moyuta)',2),
			 ('Pantaleon, S.A. (Exportación La Vega)',2),
			 ('Recursos Geotermicos, S. A.',2),
			 ('Redes Eléctricas De Centroamérica, S.A.',2),
			 ('Renace, S. A. (Exportación Moyuta)',2),
			 ('Renace, S. A. (Exportación Panaluya)',2),
			 ('San Diego, S.A. (Exportación Panaluya)',2),
			 ('Solaris Guatemala, S. A.',2),
			 ('Termica, S. A. (Exportación La Vega)',2),
			 ('Transmisora De Energia Renovable S. A.',2),
			 ('Transportadora De Energia De Centroamerica, S. A.',2),
			 ('Transporte De Energía Eléctrica Del Norte, S. A.',2),
			 ('Transportista Electrica Centroamericana, S. A.',2),
			 ('Xolhuitz Providencia, S. A. (Exportación Moyuta)',2),


			('EEB INGENIERÍA Y SERVICIOS, S. A.', 3),
			('EMPRESA DE TRANSPORTE Y CONTROL DE ENERGÍA ELÉCTRICA, INDE', 3),
			('ORAZUL ENERGY GUATEMALA TRANSCO, LIMITADA', 3),
			('REDES ELÉCTRICAS DE CENTROAMÉRICA, S. A.', 3),
			('TRANSFOSUR, S. A.', 3),
			('TRANSMISORA DE ENERGIA RENOVABLE, S. A.', 3),
			('TRANSPORTADORA DE ENERGIA DE CENTROAMERICA, S. A.', 3),
			('TRANSPORTE DE ELECTRICIDAD DE OCCIDENTE', 3),
			('TRANSPORTE DE ENERGÍA ELÉCTRICA DEL NORTE, S. A.', 3),
			('TRANSPORTES ELECTRICOS DEL SUR, S. A.', 3),
			('TRANSPORTISTA ELÉCTRICA CENTROAMERICANA, S. A.', 3);